import React from "react";
import Head from "next/head";

// Sections
import HeadlineSection from "../sections/Headline";
import AvailableProducts from "../sections/AvailableProducts";
import WhoItIsIndicatedSection from "../sections/WhoItIsIndicated";
import SmartphoneScreenshotsSection from "../sections/SmartphoneScreenshots";
import DoubtsSection from "../sections/Doubts";

const Home: React.FC = () => (
  <div>
    <Head>
      <title>Create Next App 2</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="true"
      />
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap"
      />
    </Head>

    <HeadlineSection />
    <AvailableProducts />
    <WhoItIsIndicatedSection />
    <SmartphoneScreenshotsSection />
    <DoubtsSection />
  </div>
);

export default Home;
