import React from 'react';
import Head from '../../node_modules/next/head';

import LoginIllustration from '../assets/login_illustration.svg';

const Home: React.FC = () =>  {
  return (
    <div>
      <Head>
        <title>Create Next App 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <img src={LoginIllustration} alt="teste" />
        <h1>Hello World!</h1>
      </main>
    </div>
  );
}

export default Home
